const products = [
  {
    id: 1,
    name: "AMBUSH ",
    desc: "Nike Air Force 1 Low",
    price: 750,
    image:
      "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id1.jpg",
  },
  {
    id: 2,
    name: "Fly Streetwear",
    desc: "Nike SB Dunk Low 2023",
    price: 759,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id2.jpg",
  },
  {
    id: 3,
    name: "Dunk Low SE ",
    desc: "Nike Dunk Low SE 2023",
    price: 725,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id3.jpg",
  },
  {
    id:4,
    name: "Kobe 7 ",
    desc: "Nike Zoom Kobe 7 Gold Medal",
    price:890 ,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id4.jpg",
  },
  {
    id:5,
    name: "Air Jordan 1 Low ",
    desc: "Alternate Bred Toe",
    price:675,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id5.jpg",
  },
  {
    id:6,
    name: "Nike Dunk Low",
    desc: "Industrial Blue",
    price:675,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784365/tenis/id6.jpg",
  },
  {
    id:7,
    name: "Jarritos x ",
    desc: "Nike SB Dunk Low",
    price:680,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id7.jpg",
  },
  {
    id:8,
    name: "Panda",
    desc: " Air Jordan 1 Low",
    price:630,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id8.jpg",
  },
  {
    id:9,
    name: "Midnight Navy ",
    desc: "Nike Dunk Low “Midnight Navy”",
    price:720,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id9.jpg",
  },
  {
    id:10,
    name: "Light blue",
    desc: "Nike SB Dunk Low",
    price:720,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id10.jpg",
  },
  {
    id:11,
    name: "Light Orewood Brown",
    desc: "2023 New Nike Dunk Low ",
    price:735,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id11.jpg",
  },
  {
    id:12,
    name: "Reverse Brazil ",
    desc: "Nike Dunk Low ",
    price:789,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id12.jpg",
  },
  {
    id:13,
    name: "Light Iron Ore",
    desc: "Nike Dunk Low ",
    price:817,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784367/tenis/id13.jpg",
  },
  {
    id:14,
    name: " Low Retro SP ",
    desc: "Nike SB Dunk Low Retro SP",
    price:640,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784367/tenis/id14.jpg",
  },
  {
    id:15,
    name: " Grey Leather ",
    desc: " Nike SB Dunk Low 2023",
    price:717,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784367/tenis/id15.jpg",
  },
  {
    id:16,
    name: "Scrap Premium",
    desc: "Nike Dunk Low Scrap Premium",
    price:750,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784367/tenis/id16.jpg",
  },
  {
    id:17,
    name: "Travis Scott ",
    desc: "Travis Scott x Air Jordan 1 Low OG AJ1",
    price:720,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784366/tenis/id7.jpg",
  },
  {
    id:18,
    name: " Dark",
    desc: "Nike SB Low Dark",
    price:817,
    image: "https://res.cloudinary.com/pokersites/image/upload/v1677784367/tenis/id18.jpg",
  }

];

module.exports = products;
